; This file was auto-generated by drush_make
api = 2

core = 6.x

projects[pressflow][type] = "core"
projects[pressflow][download][type] = "get"
projects[pressflow][download][url] = "http://files.pressflow.org/pressflow-6-current.tar.gz"




; Modules
projects[admin_menu][version] = "1.8"

projects[ctools][version] = "1.8"

projects[event][version] = "2.x-dev"

projects[cck][version] = "2.9"

projects[content_taxonomy][subdir] = "sites/all/modules/contrib/content_taxonomy"
projects[content_taxonomy][version] = "1.0-rc2"

projects[custom_pagers][subdir] = "sites/all/modules/contrib/custom_pagers"
projects[custom_pagers][version] = "1.0-beta2"

projects[date][subdir] = "sites/all/modules/contrib/date"
projects[date][version] = "2.8"

projects[devel][version] = "1.26"

projects[emfield][version] = "2.4"

projects[exhibit][subdir] = "sites/all/modules/contrib/exhibit"
projects[exhibit][version] = "1.0-beta1"

projects[features_extra][subdir] = "sites/all/modules/contrib/features_extra"
projects[features_extra][version] = "1.x-dev"

projects[features][version] = "1.2"

projects[features_override][subdir] = "sites/all/modules/contrib/features_override"
projects[features_override][version] = "1.0-beta2"

projects[features_plumber][subdir] = "sites/all/modules/contrib/features_plumber"
projects[features_plumber][version] = "1.0-alpha1"

projects[filefield][subdir] = "sites/all/modules/contrib/filefield"
projects[filefield][version] = "3.10"

projects[heartbeat][subdir] = "sites/all/modules/contrib/heartbeat"
projects[heartbeat][version] = "4.9"

projects[image_fupload][version] = "3.0-rc2"

projects[imageapi][subdir] = "sites/all/modules/contrib/imageapi"
projects[imageapi][version] = "1.10"

projects[imagecache][subdir] = "sites/all/modules/contrib/imagecache"
projects[imagecache][version] = "2.0-beta12"

projects[imagefield][subdir] = "sites/all/modules/contrib/imagefield"
projects[imagefield][version] = "3.10"

projects[libraries][version] = "1.0"

projects[link][subdir] = "sites/all/modules/contrib/link"
projects[link][version] = "2.9"

projects[location][version] = "3.1"

projects[masquerade][version] = "1.7"

projects[menu_attributes][subdir] = "sites/all/modules/contrib/menu_attributes"
projects[menu_attributes][version] = "2.0-beta1"

projects[menu_block][version] = "2.4"

projects[messaging][subdir] = "sites/all/modules/contrib/messaging"
projects[messaging][version] = "2.4"

projects[nice_menus][subdir] = "sites/all/modules/contrib/nice_menus"
projects[nice_menus][version] = "2.1"

projects[nodehierarchy][subdir] = "sites/all/modules/contrib/nodehierarchy"
projects[nodehierarchy][version] = "2.1"

projects[nodereference_url][subdir] = "sites/all/modules/contrib/nodereference_url"
projects[nodereference_url][version] = "1.11"

projects[nodereference_views][subdir] = "sites/all/modules/contrib/nodereference_views"
projects[nodereference_views][version] = "1.3"

projects[notifications][subdir] = "sites/all/modules/contrib/notifications"
projects[notifications][version] = "2.3"

projects[og][version] = "2.2"

projects[og_user_roles][subdir] = "sites/all/modules/contrib/og_user_roles"
projects[og_user_roles][version] = "4.1"

projects[panels][version] = "3.10"

projects[realname][subdir] = "sites/all/modules/contrib/realname"
projects[realname][version] = "1.4"

projects[realname_userreference][subdir] = "sites/all/modules/contrib/realname_userreference"
projects[realname_userreference][version] = "1.2"

projects[rsvp][version] = "2.0"

projects[simplenews][version] = "2.0-alpha3"

projects[strongarm][subdir] = "sites/all/modules/contrib/strongarm"
projects[strongarm][version] = "2.1"

projects[token][version] = "1.18"

projects[user_relationships][version] = "1.0"

projects[uuid][version] = "1.0-beta2"

projects[uuid_features][subdir] = "sites/all/modules/contrib/uuid_features"
projects[uuid_features][version] = "1.0-alpha1"

projects[viewfield][subdir] = "sites/all/modules/contrib/viewfield"
projects[viewfield][version] = "1.2"

projects[views][subdir] = "sites/all/modules"
projects[views][version] = "2.16"

projects[views_attach][subdir] = "sites/all/modules/contrib/views_attach"
projects[views_attach][version] = "2.2"

projects[views_customfield][subdir] = "sites/all/modules/contrib/views_customfield"
projects[views_customfield][version] = "1.0"

projects[views_gallery][subdir] = "sites/all/modules/contrib/views_gallery"
projects[views_gallery][version] = "2.0-beta2"

projects[views_or][subdir] = "sites/all/modules/contrib/views_or"
projects[views_or][version] = "1.0-alpha1"

projects[views_slideshow][subdir] = "sites/all/modules"
projects[views_slideshow][version] = "3.0"

projects[wysiwyg][version] = "2.4"

; Themes
projects[rubik][version] = "3.0-beta2"

; Modules
; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[apachesolr_users][download][type] = "git"
projects[apachesolr_users][download][url] = "git://github.com/SupermanScott/apachesolr_users.git"
projects[apachesolr_users][type] = "module"
projects[apachesolr_users][subdir] = "sites/all/modules/noncontrib"


; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
;projects[imagemanager][download][type] = ""
;projects[imagemanager][download][url] = ""
;projects[imagemanager][type] = "module"
;projects[imagemanager][subdir] = "sites/all/modules/noncontrib"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
;projects[panels_extra_layouts][download][type] = ""
;projects[panels_extra_layouts][download][url] = ""
;projects[panels_extra_layouts][type] = "module"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[wysiwyg_panels][download][type] = "git"
projects[wysiwyg_panels][download][url] = "git://github.com/WI1/wysiwyg_panels.git"
projects[wysiwyg_panels][type] = "module"
projects[wysiwyg_panels][subdir] = "sites/all/modules/noncontrib"

;
; Own modules
;

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[balanceonline_contact_person][download][type] = "git"
projects[balanceonline_contact_person][download][url] = "git://github.com/WI1/balanceonline_contact_person.git"
projects[balanceonline_contact_person][type] = "module"
projects[balanceonline_contact_person][subdir] = "sites/all/modules/custom"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[balanceonline_custom_form][download][type] = "git"
projects[balanceonline_custom_form][download][url] = "git://github.com/WI1/balanceonline_custom_form.git"
projects[balanceonline_custom_form][type] = "module"
projects[balanceonline_custom_form][subdir] = "sites/all/modules/custom"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[balanceonline_eventform][download][type] = "git"
projects[balanceonline_eventform][download][url] = "git://github.com/WI1/balanceonline_event_form.git"
projects[balanceonline_eventform][type] = "module"
projects[balanceonline_eventform][subdir] = "sites/all/modules/custom"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[balanceonline_og_like][download][type] = "git"
projects[balanceonline_og_like][download][url] = "git://github.com/WI1/balanceonline_og_like.git"
projects[balanceonline_og_like][type] = "module"
projects[balanceonline_og_like][subdir] = "sites/all/modules/custom"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[biblio_mendeley][download][type] = "git"
projects[biblio_mendeley][download][url] = "git://github.com/jakob-stoeck/drupal-biblio-mendeley.git"
projects[biblio_mendeley][type] = "module"
projects[biblio_mendeley][subdir] = "sites/all/modules/custom"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
;projects[clicks_tracking][download][type] = ""
;projects[clicks_tracking][download][url] = ""
;projects[clicks_tracking][type] = "module"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[conftool_connect][download][type] = "git"
projects[conftool_connect][download][url] = "git://github.com/jakob-stoeck/drupal-conftool.git"
projects[conftool_connect][type] = "module"
projects[conftool_connect][subdir] = "sites/all/modules/custom"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[focus_groups][download][type] = "git"
projects[focus_groups][download][url] = "git://github.com/WI1/focus_groups.git"
projects[focus_groups][type] = "module"
projects[focus_groups][subdir] = "sites/all/modules/custom/focus_groups"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[footer_sitemap][download][type] = "git"
projects[footer_sitemap][download][url] = "git://github.com/WI1/footer_sitemap.git"
projects[footer_sitemap][type] = "module"
projects[footer_sitemap][subdir] = "sites/balanceonline.org/modules/custom"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[heartbeat_tab][download][type] = "git"
projects[heartbeat_tab][download][url] = "git://github.com/WI1/heartbeat_tab.git"
projects[heartbeat_tab][type] = "module"
projects[heartbeat_tab][subdir] = "sites/all/modules/custom"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[js_redirect][download][type] = "git"
projects[js_redirect][download][url] = "git://github.com/jakob-stoeck/drupal-js-redirect.git"
projects[js_redirect][type] = "module"
projects[js_redirect][subdir] = "sites/all/modules/custom"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
; old dependency which is not needed anymore
;projects[mendeley][download][type] = ""
;projects[mendeley][download][url] = ""
:projects[mendeley][type] = "module"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[node_heartbeat][download][type] = "git"
projects[node_heartbeat][download][url] = "git://github.com/WI1/node_heartbeat.git"
projects[node_heartbeat][type] = "module"
projects[node_heartbeat][subdir] = "sites/all/modules/custom"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[nodehierarchy_downloads][download][type] = "git"
projects[nodehierarchy_downloads][download][url] = "git://github.com/WI1/nodehierarchy_downloads.git"
projects[nodehierarchy_downloads][type] = "module"
projects[nodehierarchy_downloads][subdir] = "sites/all/modules/custom"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[og_invite][download][type] = "git"
projects[og_invite][download][url] = "git://github.com/WI1/og_invite.git"
projects[og_invite][type] = "module"
projects[og_invite][subdir] = "sites/all/modules/custom"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[projecttabs][download][type] = "git"
projects[projecttabs][download][url] = "git://github.com/WI1/projecttabs.git"
projects[projecttabs][type] = "module"
projects[projecttabs][subdir] = "sites/all/modules/custom"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
; old dependency that couldn't be found anymore, skipped in favor of ur_mutualfriends
; projects[ur_common_friends][download][type] = ""
; projects[ur_common_friends][download][url] = ""
; projects[ur_common_friends][type] = "module"
; projects[ur_common_friends][subdir] = "sites/all/modules/custom"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[ur_mutualfriends][download][type] = "git"
projects[ur_mutualfriends][download][url] = "git://github.com/WI1/ur_mutualfriends.git"
projects[ur_mutualfriends][type] = "module"
projects[ur_mutualfriends][subdir] = "sites/all/modules/custom"

;
; Features
;

projects[wi1init][download][type] = "git"
projects[wi1init][download][url] = "git://github.com/WI1/wi1init.git"
projects[wi1init][type] = "module"
projects[wi1init][subdir] = "sites/all/modules/features"

projects[activity][download][type] = "git"
projects[activity][download][url] = "git://github.com/WI1/BALANCE_activity.git"
projects[activity][type] = "module"
projects[activity][subdir] = "sites/all/modules/features"

projects[balance_init][download][type] = "git"
projects[balance_init][download][url] = "git://github.com/WI1/balance_init.git"
projects[balance_init][type] = "module"
projects[balance_init][subdir] = "sites/all/modules/features"

projects[events][download][type] = "git"
projects[events][download][url] = "git://github.com/WI1/BALANCE_events.git"
projects[events][type] = "module"
projects[events][subdir] = "sites/all/modules/features"

projects[groups][download][type] = "git"
projects[groups][download][url] = "git://github.com/WI1/BALANCE_groups.git"
projects[groups][type] = "module"
projects[groups][subdir] = "sites/all/modules/features"

projects[map][download][type] = "git"
projects[map][download][url] = "git://github.com/WI1/BALANCE_map.git"
projects[map][type] = "module"
projects[map][subdir] = "sites/all/modules/features"

projects[pressclippings][download][type] = "git"
projects[pressclippings][download][url] = "git://github.com/WI1/BALANCE_publications.git"
projects[pressclippings][type] = "module"
projects[pressclippings][subdir] = "sites/all/modules/features"

projects[publications][download][type] = "git"
projects[publications][download][url] = "git://github.com/WI1/BALANCE_publications.git"
projects[publications][type] = "module"
projects[publications][subdir] = "sites/all/modules/features"

projects[videos][download][type] = "git"
projects[videos][download][url] = "git://github.com/WI1/BALANCE_video.git"
projects[videos][type] = "module"
projects[videos][subdir] = "sites/all/modules/features"

projects[wiki][download][type] = "git"
projects[wiki][download][url] = "git://github.com/WI1/BALANCE_wiki.git"
projects[wiki][type] = "module"
projects[wiki][subdir] = "sites/all/modules/features"

projects[wiipod_feats][download][type] = "git"
projects[wiipod_feats][download][url] = "git://github.com/harryster/wiipod-feats.git"
projects[wiipod_feats][type] = "module"
projects[wiipod_feats][version] = "1.1"



; Themes
; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[balance][download][type] = "git"
projects[balance][download][url] = "git://redmine.wi1projects.com/wiipod.git"
projects[balance][type] = "theme"

