; This file was auto-generated by drush_make
api = 2

core = 6.x

projects[pressflow][type] = "core"
projects[pressflow][download][type] = "get"
projects[pressflow][download][url] = "http://files.pressflow.org/pressflow-6-current.tar.gz"



; Modules
projects[views_bulk_operations][version] = "1.x-dev"

projects[addresses][version] = "1.11"

projects[admin_menu][version] = "1.8"

projects[adminrole][version] = "1.3"

projects[advanced_help][version] = "1.2"

projects[ajax_load][version] = "1.3"

projects[apachesolr][version] = "1.x-dev"

projects[apachesolr_ajax][version] = "1.11"

projects[apachesolr_autocomplete][version] = "1.2"

projects[apachesolr_biblio][version] = "1.x-dev"

projects[auto_nodetitle][subdir] = "sites/all/modules/contrib/auto_nodetitle"
projects[auto_nodetitle][version] = "1.2"

projects[autoload][version] = "2.0"

projects[backreference][version] = "1.1"

projects[better_formats][version] = "1.2"

projects[biblio][version] = "2.x-dev"

projects[boxes][subdir] = "sites/all/modules/contrib/boxes"
projects[boxes][version] = "1.0"

projects[browscap][version] = "1.1"

projects[ctools][version] = "1.8"

projects[calendar][version] = "2.x-dev"

projects[event][version] = "2.x-dev"

projects[checkbox_validate][version] = "2.1"

projects[cmf][version] = "2.0"

projects[codefilter][version] = "1.0"

projects[contemplate][version] = "1.2"

projects[cck][version] = "2.9"

projects[content_access][version] = "1.2"

projects[content_taxonomy][version] = "1.0-rc2"

projects[context][version] = "3.0"

projects[css_gzip][version] = "1.3"

projects[custom_pagers][version] = "1.x-dev"

projects[date][version] = "2.7"

projects[db_maintenance][version] = "1.3"

projects[dbtuner][version] = "1.0-alpha2"

projects[devel][version] = "1.23"

projects[diff][version] = "2.1"

projects[drupalforfirebug][version] = "1.4"

projects[editablefields][version] = "3.x-dev"

projects[emfield][version] = "2.4"

projects[event_views][version] = "2.4"

projects[evoc][version] = "1.x-dev"

projects[exhibit][version] = "1.x-dev"

projects[faq][version] = "1.12"

projects[features_extra][subdir] = "sites/all/modules/contrib/features_extra"
projects[features_extra][version] = "1.x-dev"

projects[features][version] = "1.0"

projects[features_plumber][subdir] = "sites/all/modules/contrib/features_plumber"
projects[features_plumber][version] = "1.0-alpha1"

projects[ftools][subdir] = "sites/all/modules/contrib/ftools"
projects[ftools][version] = "1.3"

projects[feedback][version] = "2.1"

projects[filefield][version] = "3.10"

projects[filter_perms][version] = "1.1"

projects[flag][version] = "1.3"

projects[heartbeat][version] = "4.10"

projects[flexifilter][version] = "1.2"


projects[footnotes][version] = "2.5"

projects[gmap][version] = "1.1"

projects[headerimage][version] = "1.x-dev"

projects[hover_preview][version] = "1.0"

projects[image][version] = "1.1"

projects[image_fupload][version] = "3.0-rc2"

projects[imageapi][version] = "1.10"

projects[imagecache][version] = "2.0-beta10"

projects[imagecache_actions][version] = "1.8"

projects[imagecache_profiles][version] = "1.3"

projects[imagefield][version] = "3.10"

projects[insert_block][version] = "1.x-dev"

projects[invite][version] = "2.0-beta3"

projects[javascript_aggregator][version] = "1.5"

projects[jquery_ui][version] = "1.5"

projects[jquery_update][version] = "2.0-alpha1"

projects[l10n_update][version] = "1.0-alpha3"

projects[ldap_integration][version] = "1.0-beta2"

projects[link][version] = "2.9"

projects[location][version] = "3.1"

projects[masquerade][version] = "1.7"

projects[media_vimeo][version] = "1.1"

projects[menu_attributes][version] = "1.4"

projects[menu_block][version] = "2.4"

projects[menutrails][version] = "1.1"

projects[messaging][version] = "2.4"

projects[nice_menus][version] = "2.1"

projects[node_export][version] = "2.24"

projects[node_import][version] = "1.1"

projects[nodehierarchy][version] = "1.4"

projects[nodequeue][version] = "2.9"

projects[nodereference_url][version] = "1.11"

projects[nodereference_views][version] = "1.3"

projects[notifications][version] = "2.3"

projects[office_html][version] = "1.1"

projects[og][version] = "2.1"

projects[og_user_roles][version] = "1.5"

projects[onepageprofile][version] = "1.11"

projects[openlayers][version] = "2.0-alpha10"

projects[panels][version] = "3.9"

projects[path_alias_xt][version] = "1.2"

projects[path_redirect][version] = "1.0-rc2"

projects[pathauto][version] = "2.0-rc2"

projects[pathologic][version] = "3.4"

projects[piwik][version] = "2.1"

projects[rdf][version] = "1.0-alpha8"

projects[realname][version] = "1.4"

projects[realname_userreference][version] = "1.2"

projects[reverse_node_reference][version] = "1.0"

projects[rsvp][version] = "2.0"

projects[rules][version] = "1.4"

projects[signup][version] = "1.0"

projects[simplenews][version] = "1.3"

projects[site_map][version] = "2.2"

projects[smtp][version] = "1.x-dev"

projects[spaces][version] = "3.1"

projects[sparql][version] = "1.0-alpha1"

projects[strongarm][version] = "2.0"

projects[tableofcontents][version] = "3.6"

projects[tabs][version] = "1.3"

projects[tagadelic_views][version] = "1.2"

projects[talk][version] = "1.6"

projects[taxonomy_manager][version] = "2.2"

projects[taxonomy_node][subdir] = "sites/all/modules/contrib/taxonomy_node"
projects[taxonomy_node][version] = "1.0-beta3"

projects[token][version] = "1.16"

projects[token_profile][subdir] = "sites/all/modules/contrib/token_profile"
projects[token_profile][version] = "1.0-beta1"

projects[transliteration][version] = "3.0"

projects[unfuddle_api][version] = "1.x-dev"

projects[unfuddle_feedback][version] = "1.1"

projects[user_relationships][version] = "1.0"

projects[uuid][subdir] = "sites/all/modules/contrib/uuid"
projects[uuid][version] = "1.0-beta2"

projects[uuid_features][subdir] = "sites/all/modules/contrib/uuid_features"
projects[uuid_features][version] = "1.0-alpha1"

projects[varnish][version] = "1.x-dev"

projects[vertical_tabs][version] = "1.0-rc2"

projects[viewfield][version] = "1.1"

projects[views][version] = "3.x-dev"

projects[views_hacks][subdir] = "sites/all/modules/contrib/views_hacks"
projects[views_hacks][version] = "1.0-beta1"

projects[views_attach][version] = "2.2"

projects[views_customfield][version] = "1.0"

projects[views_gallery][version] = "1.3"

projects[views_groupby][version] = "1.0-rc2"

projects[views_or][version] = "1.x-dev"

;projects[views_slideshow][version] = "2.0"

projects[views_tabs][version] = "1.0-beta1"

projects[vt_default][version] = "1.0-rc3"

projects[wikitools][version] = "1.2"

projects[wysiwyg][version] = "2.4"


; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
; module abandoned if required by feature dep needs to be remove
;projects[og_forum][download][type] = ""
;projects[og_forum][download][url] = ""
;projects[og_forum][type] = "module"
;projects[og_forum][version] = "2.2"


;
; Non-Drupal.org hosted Modules
;

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[apachesolr_users][download][type] = "git"
projects[apachesolr_users][download][url] = "git://github.com/SupermanScott/apachesolr_users.git"
projects[apachesolr_users][type] = "module"
projects[apachesolr_users][subdir] = "noncontrib"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
;projects[imagemanager][download][type] = ""
;projects[imagemanager][download][url] = ""
;projects[imagemanager][type] = "module"
;projects[imagemanager][subdir] = "noncontrib"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
;projects[panels_extra_layouts][download][type] = ""
;projects[panels_extra_layouts][download][url] = ""
;projects[panels_extra_layouts][type] = "module"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[wysiwyg_panels][download][type] = "git"
projects[wysiwyg_panels][download][url] = "git://github.com/WI1/wysiwyg_panels.git"
projects[wysiwyg_panels][type] = "module"
projects[wysiwyg_panels][subdir] = "noncontrib"

;
; Own modules
;

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[balanceonline_contact_person][download][type] = "git"
projects[balanceonline_contact_person][download][url] = "git://github.com/WI1/balanceonline_contact_person.git"
projects[balanceonline_contact_person][type] = "module"
projects[balanceonline_contact_person][subdir] = "custom"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[balanceonline_custom_form][download][type] = "git"
projects[balanceonline_custom_form][download][url] = "git://github.com/WI1/balanceonline_custom_form.git"
projects[balanceonline_custom_form][type] = "module"
projects[balanceonline_custom_form][subdir] = "custom"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[balanceonline_eventform][download][type] = "git"
projects[balanceonline_eventform][download][url] = "git://github.com/WI1/balanceonline_event_form.git"
projects[balanceonline_eventform][type] = "module"
projects[balanceonline_eventform][subdir] = "custom"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[balanceonline_og_like][download][type] = "git"
projects[balanceonline_og_like][download][url] = "git://github.com/WI1/balanceonline_og_like.git"
projects[balanceonline_og_like][type] = "module"
projects[balanceonline_og_like][subdir] = "custom"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[biblio_mendeley][download][type] = "git"
projects[biblio_mendeley][download][url] = "git://github.com/jakob-stoeck/drupal-biblio-mendeley.git"
projects[biblio_mendeley][type] = "module"
projects[biblio_mendeley][subdir] = "custom"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
;projects[clicks_tracking][download][type] = ""
;projects[clicks_tracking][download][url] = ""
;projects[clicks_tracking][type] = "module"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[conftool_connect][download][type] = "git"
projects[conftool_connect][download][url] = "git://github.com/jakob-stoeck/drupal-conftool.git"
projects[conftool_connect][type] = "module"
projects[conftool_connect][subdir] = "custom"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[focus_groups][download][type] = "git"
projects[focus_groups][download][url] = "git://github.com/WI1/focus_groups.git"
projects[focus_groups][type] = "module"
projects[focus_groups][subdir] = "custom"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[footer_sitemap][download][type] = "git"
projects[footer_sitemap][download][url] = "git://github.com/WI1/footer_sitemap.git"
projects[footer_sitemap][type] = "module"
projects[footer_sitemap][subdir] = "custom"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[heartbeat_tab][download][type] = "git"
projects[heartbeat_tab][download][url] = "git://github.com/WI1/heartbeat_tab.git"
projects[heartbeat_tab][type] = "module"
projects[heartbeat_tab][subdir] = "custom"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[js_redirect][download][type] = "git"
projects[js_redirect][download][url] = "git://github.com/jakob-stoeck/drupal-js-redirect.git"
projects[js_redirect][type] = "module"
projects[js_redirect][subdir] = "custom"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
; old dependency which is not needed anymore
;projects[mendeley][download][type] = ""
;projects[mendeley][download][url] = ""
:projects[mendeley][type] = "module"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[node_heartbeat][download][type] = "git"
projects[node_heartbeat][download][url] = "git://github.com/WI1/node_heartbeat.git"
projects[node_heartbeat][type] = "module"
projects[node_heartbeat][subdir] = "custom"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[nodehierarchy_downloads][download][type] = "git"
projects[nodehierarchy_downloads][download][url] = "git://github.com/WI1/nodehierarchy_downloads.git"
projects[nodehierarchy_downloads][type] = "module"
projects[nodehierarchy_downloads][subdir] = "custom"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[og_invite][download][type] = "git"
projects[og_invite][download][url] = "git://github.com/WI1/og_invite.git"
projects[og_invite][type] = "module"
projects[og_invite][subdir] = "custom"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[projecttabs][download][type] = "git"
projects[projecttabs][download][url] = "git://github.com/WI1/projecttabs.git"
projects[projecttabs][type] = "module"
projects[projecttabs][subdir] = "custom"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
; old dependency that couldn't be found anymore, skipped in favor of ur_mutualfriends
;projects[ur_common_friends][download][type] = ""
;projects[ur_common_friends][download][url] = ""
;projects[ur_common_friends][type] = "module"
;projects[ur_common_friends][subdir] = "custom"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[ur_mutualfriends][download][type] = "git"
projects[ur_mutualfriends][download][url] = "git://github.com/WI1/ur_mutualfriends.git"
projects[ur_mutualfriends][type] = "module"
projects[ur_mutualfriends][subdir] = "custom"




;
; Features
;

projects[wi1init][download][type] = "git"
projects[wi1init][download][url] = "git://github.com/WI1/wi1init.git"
projects[wi1init][type] = "module"
projects[wi1init][subdir] = "cfeatures"

projects[activity][download][type] = "git"
projects[activity][download][url] = "git://github.com/WI1/BALANCE_activity.git"
projects[activity][type] = "module"
projects[activity][subdir] = "cfeatures"

projects[balance_init][download][type] = "git"
projects[balance_init][download][url] = "git://github.com/WI1/balance_init.git"
projects[balance_init][type] = "module"
projects[balance_init][subdir] = "cfeatures"

projects[events][download][type] = "git"
projects[events][download][url] = "git://github.com/WI1/BALANCE_events.git"
projects[events][type] = "module"
projects[events][subdir] = "cfeatures"

projects[groups][download][type] = "git"
projects[groups][download][url] = "git://github.com/WI1/BALANCE_groups.git"
projects[groups][type] = "module"
projects[groups][subdir] = "cfeatures"

projects[user_profiles][download][type] = "git"
projects[user_profiles][download][url] = "git://github.com/WI1/Balance-User-Profiles.git"
projects[user_profiles][type] = "module"
projects[user_profiles][subdir] = "cfeatures"

projects[map][download][type] = "git"
projects[map][download][url] = "git://github.com/WI1/BALANCE_map.git"
projects[map][type] = "module"
projects[map][subdir] = "cfeatures"

projects[pressclippings][download][type] = "git"
projects[pressclippings][download][url] = "git://github.com/WI1/BALANCE_pressclippings.git"
projects[pressclippings][type] = "module"
projects[pressclippings][subdir] = "cfeatures"

projects[publications][download][type] = "git"
projects[publications][download][url] = "git://github.com/WI1/BALANCE_publications.git"
projects[publications][type] = "module"
projects[publications][subdir] = "cfeatures"

projects[videos][download][type] = "git"
projects[videos][download][url] = "git://github.com/WI1/BALANCE_video.git"
projects[videos][type] = "module"
projects[videos][subdir] = "cfeatures"

projects[wiki][download][type] = "git"
projects[wiki][download][url] = "git://github.com/WI1/BALANCE_wiki.git"
projects[wiki][type] = "module"
projects[wiki][subdir] = "cfeatures"


; Themes
; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[balance][download][type] = "git"
projects[balance][download][url] = "git://github.com/WI1/wiipod-theme.git"
projects[balance][type] = "theme"







