; This file was auto-generated by drush_make
core = 7.x

api = 2
projects[drupal][version] = "7.10"

; Profiles
; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[standard][download][type] = ""
projects[standard][download][url] = ""
projects[standard][type] = "profile"

; Modules
projects[ctools][version] = "1.0-rc1"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[cck][download][type] = ""
projects[cck][download][url] = ""
projects[cck][type] = "module"
projects[cck][version] = "2.x-dev"

projects[ckeditor][version] = "1.6"

projects[entity][version] = "1.0-rc1"

projects[libraries][version] = "1.0"

projects[mollom][version] = "1.1"

projects[og][version] = "1.3"

projects[views][version] = "3.1"

